name: bmi_diary
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_neumorphic: ^3.0.2
  stacked: ^1.7.6
  flutter_icons: ^1.1.0
  stacked_services: ^0.5.2
  provider: ^4.3.2
  get_it: ^4.0.4
  intl: ^0.16.1
  flutter_sinusoidals: ^0.1.3
  carousel_slider: ^2.2.1
  smooth_page_indicator: ^0.2.0
  sqflite: null
  path: null
  crypto: ^2.1.5
  shared_preferences: ^0.5.10

  cupertino_icons: ^0.1.3
  flutter_cupertino_localizations: ^1.0.1
  rect_getter: ^0.1.0
  fl_chart: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - locales/EN_US.json
    - locales/PL_PL.json

